name: Push to Docker Hub

on:
  push:
    branches:
      - master
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            macia/atractive-smithers:latest
            macia/atractive-smithers:${{ github.sha }}
  deploy:
    runs-on: ubuntu-latest
    needs: build-docker-image
    environment: prod
    steps:
      - name: Deploy
        run: |
          curl --location '${{ secrets.COOLIFY_DOMAIN }}/deploy?uuid=${{ secrets.COOLIFY_RESOURCE_ID }}' \
          --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}' \
          --header 'Content-Type: application/json'